version: '3'

services:
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=WPF_Django
      - DB_USER=root
      - DB_PASSWORD=your_password
      - DB_PORT=3306

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=WPF_Django
      - MYSQL_ROOT_PASSWORD=your_password
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data: 